import Header from "../components/Header";
import Footer from "../components/Footer";
import CheckOutLabel from "../components/CheckOutLabel";
import "./globals.css";
import { Manrope } from "next/font/google";

const inter = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <CheckOutLabel />
        <Footer />
      </body>
    </html>
  );
}
